# Generated by Django 3.2.16 on 2022-12-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20221219_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'to_do'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='to_do', max_length=50),
        ),
    ]
