# Generated by Django 3.2.16 on 2022-12-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, 'High'), (2, 'Normal'), (1, 'Low')], default=2),
        ),
    ]
