# Generated by Django 3.2.16 on 2022-12-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='Title',
            new_name='title',
        ),
    ]
